version: "3.8"

services:
  ###############################################
  # The Oracle DB Definition
  ###############################################
  soadb:
    image: ${DC_REGISTRY_DB}/database/enterprise:12.2.0.1
    ports:
      - "${DC_ORCL_PORT}:1521"
      - "${DC_ORCL_OEM_PORT}:5500"
    environment:
      - ORACLE_SID=${DC_ORCL_SID}
      #- ORACLE_SID=${DB_SID}
      - DB_SID=${DB_SID}
      - ORACLE_PDB=${DC_ORCL_PDB}
      - DB_PDB=${DB_PDB}
      - ORACLE_PWD=${DC_ORCL_SYSPWD}
      - DB_PWD=${DB_PWD}
    container_name: soadb
    volumes:
      - /Users/maxmonterrey/MyWork/Docker/OracleSOASuite/software/docker/dbdata:/opt/oracle/oradata
    networks:
      - soanet

  ###############################################
  # The SOA Admin Server
  ###############################################
  soaas:
    image: ${DC_REGISTRY_SOA}/middleware/soasuite:${DC_SOA_VERSION}-200418
    #image: max/soa12213 
    container_name: soaas
    depends_on:
      - "soadb"
    #command: /bin/bash -c "sleep 300s; /u01/oracle/dockertools/createDomainAndStart.sh"
    command: /bin/bash -c "/u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    environment:
      - DOMAIN_TYPE=soaosb
      - ADMIN_HOST=soaas
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - CONNECTION_STRING=soadb:1521/mysoapdb.localdomain
      #- CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${DC_ORCL_PDB}
      #- CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}/${DB_SID}
      #- DB_PASSWORD=${DC_ORCL_SYSPWD}
      - DB_PASSWORD=${DB_PWD}
      - DB_PWD=${DB_PWD}
      - DB_SCHEMA_PASSWORD=${DC_RCU_SCHPWD}
      - RCUPREFIX=${DC_RCU_SOAPFX}
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_SOA}:/u01/oracle/user_projects
      - /Users/maxmonterrey/MyWork/Docker/OracleSOASuite/container-scripts:/u01/oracle/dockertools/
    networks:
      - soanet

  ###############################################
  # The SOA Managed Server 1
  ###############################################
  soams1:
    image:  ${DC_REGISTRY_SOA}/middleware/soasuite:${DC_SOA_VERSION}-200418
    container_name: soams1
    depends_on:
      - "soaas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
    environment:
      - DOMAIN_TYPE=soa
      - ADMIN_HOST=soaas
      - ADMIN_PORT=7001
      - adminhostname=soaas
      - adminport=7001
      - MANAGED_SERVER=soa_server1
    volumes:
      - ${DC_DDIR_SOA}:/u01/oracle/user_projects
      - /Users/maxmonterrey/MyWork/Docker/OracleSOASuite/container-scripts:/u01/oracle/dockertools/
    networks:
      - soanet

  ###############################################
  # The SOA Managed Server 2
  ###############################################
  soams2:
    image:  ${DC_REGISTRY_SOA}/middleware/soasuite:${DC_SOA_VERSION}-200418
    container_name: soams2
    depends_on:
      - "soaas"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8002:8001"
    environment:
      - DOMAIN_TYPE=soa
      - ADMIN_HOST=soaas
      - ADMIN_PORT=7001
      - adminhostname=soaas
      - adminport=7001
      - MANAGED_SERVER=soa_server2
    volumes:
      - ${DC_DDIR_SOA}:/u01/oracle/user_projects
      - /Users/maxmonterrey/MyWork/Docker/OracleSOASuite/container-scripts:/u01/oracle/dockertools/
    networks:
      - soanet
  ###############################################
  # The OSB  Managed Server 1
  ###############################################
  osbms1:
      image:  ${DC_REGISTRY_SOA}/middleware/soasuite:${DC_SOA_VERSION}-200418
      container_name: osbms1
      depends_on:
        - "soaas"
      command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
      ports:
        - "9001:9001"
       
      environment:
        - DOMAIN_TYPE=soa
        - ADMIN_HOST=soaas
        - ADMIN_PORT=7001
        - adminhostname=soaas
        - adminport=7001
        - MANAGED_SERVER=osb_server1
      volumes:
        - ${DC_DDIR_SOA}:/u01/oracle/user_projects
        - /Users/maxmonterrey/MyWork/Docker/OracleSOASuite/container-scripts:/u01/oracle/dockertools/
      networks:
        - soanet
  ###############################################
  # The OSBA Managed Server 2
  ###############################################
  osbms2:
      image:  ${DC_REGISTRY_SOA}/middleware/soasuite:${DC_SOA_VERSION}-200418
      container_name: osbms2
      depends_on:
        - "soaas"
      command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
      ports:
        - "9002:9001"
      environment:
        - DOMAIN_TYPE=soa
        - ADMIN_HOST=soaas
        - ADMIN_PORT=7001
        - adminhostname=soaas
        - adminport=7001
        - MANAGED_SERVER=osb_server2
      volumes:
        - ${DC_DDIR_SOA}:/u01/oracle/user_projects
        - /Users/maxmonterrey/MyWork/Docker/OracleSOASuite/container-scripts:/u01/oracle/dockertools/
      networks:
        - soanet

networks:
 soanet:
